module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>/tests"],
  collectCoverageFrom: [
    "shared/src/ApiError.js",
    "shared/src/constants/**/*.js",
    "shared/src/middlewares/sanitize.js",
    "shared/src/middlewares/upload.js",
    "gateway/src/middlewares/**/*.js",
    "services/auth-service/src/services/auth.service.js",
    "services/auth-service/src/services/token.service.js",
    "services/auth-service/src/routes/auth.controller.js",
    "services/auth-service/src/middlewares/serviceAuth.js",
    "services/platform-service/src/services/audit.service.js",
    "services/platform-service/src/validators/*.validator.js",
    "services/platform-service/src/middlewares/serviceAuth.js",
    "services/org-service/src/services/hierarchy.service.js",
    "services/org-service/src/services/assignments.controller.js",
    "services/org-service/src/middlewares/permission.middleware.js",
    "services/org-service/src/middlewares/hierarchy.middleware.js",
    "services/org-service/src/middlewares/serviceAuth.js",
    "!**/node_modules/**",
  ],
  setupFiles: ["<rootDir>/tests/setup/env.js"],
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  moduleNameMapper: {
    "^@pink/shared(.*)$": "<rootDir>/shared/src$1",
  },
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 60,
      functions: 80,
      lines: 80,
    },
  },
};
