services:
  - type: web
    name: pinktech-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: apixey.startup@gmail.com
      - key: SMTP_PASS
        value: ondtvqlflamputwl
      - key: SMTP_FROM
        value: apixey.startup@gmail.com
      - key: EMAIL_MODE
        value: smtp
      - key: QUEUES_ENABLED
        value: "false"
