/** Canonical permission catalog. `label` + `description` power the admin UI; seeded into Mongo. */
module.exports = [
  {
    code: "auth.login",
    module: "auth",
    action: "login",
    label: "Sign in",
    description: "Allows authentication (typically implicit for all active users).",
  },
  {
    code: "user.invite",
    module: "user",
    action: "invite",
    label: "Invite users",
    description: "Send invitations and onboard new employees with roles.",
  },
  {
    code: "user.view",
    module: "user",
    action: "view",
    label: "View users",
    description: "List and inspect people in the tenant (directory, profiles).",
  },
  {
    code: "list.users",
    module: "user",
    action: "list_team",
    label: "List users (my team tree)",
    description:
      "Open the org tree limited to people under you (same subtree as ORG employee). Intended for level-1 field roles by default.",
  },
  {
    code: "user.update",
    module: "user",
    action: "update",
    label: "Update users",
    description: "Edit user records, roles, and related profile fields.",
  },
  {
    code: "user.disable",
    module: "user",
    action: "disable",
    label: "Disable users",
    description: "Deactivate or lock accounts where supported.",
  },
  {
    code: "employee.view",
    module: "employee",
    action: "view",
    label: "View org tree",
    description: "See the organization tree and reporting structure.",
  },
  {
    code: "employee.edit",
    module: "employee",
    action: "edit",
    label: "Edit org explorer",
    description: "Edit organizational structure and reporting lines.",
  },
  {
    code: "employee.assign",
    module: "employee",
    action: "assign",
    label: "Manage roles & positions",
    description: "Assign people to positions, manage roles, and update seat occupancy. Grants all position permissions automatically.",
  },
  {
    code: "employee.manage",
    module: "employee",
    action: "manage",
    label: "Manage employees",
    description: "Access employee management tab: list employees, send credentials, reset passwords.",
  },
  {
    code: "role.view",
    module: "role",
    action: "view",
    label: "View roles & catalog",
    description: "Open the role list, permission matrix, and permission catalog API.",
  },
  {
    code: "role.assign",
    module: "role",
    action: "assign",
    label: "Assign roles to users",
    description: "Attach or change role memberships (where not limited to admins).",
  },
  {
    code: "position.create",
    module: "position",
    action: "create",
    label: "Create positions",
    description: "Add new nodes to the org chart / position tree.",
  },
  {
    code: "position.update",
    module: "position",
    action: "update",
    label: "Update positions",
    description: "Edit position titles, levels, hierarchy, and metadata.",
  },
  {
    code: "position.assign",
    module: "position",
    action: "assign",
    label: "Assign positions",
    description: "Place users into specific positions (seat operations).",
  },
  {
    code: "workflow.submit",
    module: "workflow",
    action: "submit",
    label: "Submit workflows",
    description: "Create and send workflow submissions for approval.",
  },
  {
    code: "workflow.approve",
    module: "workflow",
    action: "approve",
    label: "Approve workflows",
    description: "Approve steps and move workflows forward.",
  },
  {
    code: "workflow.reject",
    module: "workflow",
    action: "reject",
    label: "Reject workflows",
    description: "Reject submissions with reason where supported.",
  },
  {
    code: "workflow.return",
    module: "workflow",
    action: "return",
    label: "Return workflows",
    description: "Send work back to prior steps for correction.",
  },
  {
    code: "form.create",
    module: "form",
    action: "create",
    label: "Create forms",
    description: "Author or configure form definitions and schema.",
  },
  {
    code: "form.publish",
    module: "form",
    action: "publish",
    label: "Publish forms",
    description: "Publish forms for use and sharing.",
  },
  {
    code: "form.view",
    module: "form",
    action: "view",
    label: "Use forms",
    description: "Open the Forms area, fill forms, and view submissions you can access.",
  },
  {
    code: "report.view",
    module: "report",
    action: "view",
    label: "View reports",
    description: "Access reporting and analytics surfaces (also satisfies legacy notification gates).",
  },
  {
    code: "audit.view",
    module: "audit",
    action: "view",
    label: "View audit log",
    description: "Read security and compliance audit trails.",
  },
  {
    code: "tenant.manage",
    module: "tenant",
    action: "manage",
    label: "Manage tenant",
    description: "Full tenant administration: orgs, cross-tenant context, and elevated operations.",
  },
  {
    code: "kyc.manage",
    module: "kyc",
    action: "manage",
    label: "Manage KYC",
    description: "Run KYC for external users: OTP, verification status, and related records.",
  },
  {
    code: "notification.compose",
    module: "notification",
    action: "compose",
    label: "Send notifications",
    description: "Compose and send messages to eligible recipients (email, in-app, etc.).",
  },
];
