module.exports = {
  apps: [
    {
      name: "gateway",
      script: "npm",
      args: "run start:gateway",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "120M",
      env: { NODE_ENV: "production", PORT: 5001, NODE_OPTIONS: "--max-old-space-size=96" },
    },
    {
      name: "auth",
      script: "npm",
      args: "start --prefix services/auth-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4001, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "platform",
      script: "npm",
      args: "start --prefix services/platform-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4002, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "org",
      script: "npm",
      args: "start --prefix services/org-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4003, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "forms",
      script: "npm",
      args: "start --prefix services/forms-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4004, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "workflow",
      script: "npm",
      args: "start --prefix services/workflow-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4005, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "kyc",
      script: "npm",
      args: "start --prefix services/kyc-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4006, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "documents",
      script: "npm",
      args: "start --prefix services/documents-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4007, NODE_OPTIONS: "--max-old-space-size=80" },
    },
    {
      name: "notifications",
      script: "npm",
      args: "start --prefix services/notifications-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 15,
      restart_delay: 3000,
      max_memory_restart: "100M",
      env: { NODE_ENV: "production", PORT: 4008, NODE_OPTIONS: "--max-old-space-size=80" },
    },
  ],
};
