module.exports = {
  apps: [
    {
      name: "gateway",
      script: "npm",
      args: "run start:gateway",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "auth",
      script: "npm",
      args: "start --prefix services/auth-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "platform",
      script: "npm",
      args: "start --prefix services/platform-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "org",
      script: "npm",
      args: "start --prefix services/org-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "forms",
      script: "npm",
      args: "start --prefix services/forms-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "workflow",
      script: "npm",
      args: "start --prefix services/workflow-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "kyc",
      script: "npm",
      args: "start --prefix services/kyc-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "documents",
      script: "npm",
      args: "start --prefix services/documents-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "notifications",
      script: "npm",
      args: "start --prefix services/notifications-service",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
