module.exports = {
  apps: [
    {
      name: "gateway",
      script: "npm",
      args: "run dev:gateway",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "auth",
      script: "npm",
      args: "run dev:auth",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "platform",
      script: "npm",
      args: "run dev:platform",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "org",
      script: "npm",
      args: "run dev:org",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "forms",
      script: "npm",
      args: "run dev:forms",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "workflow",
      script: "npm",
      args: "run dev:workflow",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "kyc",
      script: "npm",
      args: "run dev:kyc",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "documents",
      script: "npm",
      args: "run dev:documents",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "notifications",
      script: "npm",
      args: "run dev:notifications",
      cwd: "/home/ubuntu/Pinktech",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      max_memory_restart: "256M",
      env: {
        NODE_ENV: "production",
      },
    },
  ],
};
