/** Canonical permission catalog. `label` + `description` power the admin UI; seeded into Mongo. */
module.exports = [
  {
    code: "auth.login",
    module: "auth",
    action: "login",
    label: "Sign in",
    description: "Default for all active users. Can be unchecked later to deny sign-in.",
  },
  {
    code: "user.view",
    module: "user",
    action: "view",
    label: "View employee directory",
    description: "Access the Employee Management tab and see the list of employees. Level-1 employees see their own team; admins see everyone.",
  },
  {
    code: "user.invite",
    module: "user",
    action: "invite",
    label: "Invite employees",
    description: "Send invitations to onboard new employees with roles.",
  },
  {
    code: "user.update",
    module: "user",
    action: "update",
    label: "Edit employees",
    description: "Edit employee records, roles, and profile fields.",
  },
  {
    code: "user.disable",
    module: "user",
    action: "disable",
    label: "Disable employees",
    description: "Deactivate or lock employee accounts where supported.",
  },
  {
    code: "list.users",
    module: "user",
    action: "list_team",
    label: "List my team",
    description:
      "Open the org tree limited to people under you (same subtree as ORG employee). Intended for level-1 field roles by default.",
  },
  {
    code: "user.send-credentials",
    module: "user",
    action: "send_credentials",
    label: "Send employee credentials",
    description: "Send or resend login credentials to org employees via email.",
  },
  {
    code: "employee.view",
    module: "employee",
    action: "view",
    label: "View org assignments",
    description:
      "See who sits in which positions and reporting lines (ORG Employee tab). When checked alone, shows only your direct reports. Admin / super admin sees the full org structure.",
  },
  {
    code: "employee.assign",
    module: "employee",
    action: "assign",
    label: "Manage assignments",
    description: "Assign people to positions and update seat occupancy.",
  },
  {
    code: "role.view",
    module: "role",
    action: "view",
    label: "View roles & catalog",
    description: "Open the role list, permission matrix, and permission catalog API.",
  },
  {
    code: "role.assign",
    module: "role",
    action: "assign",
    label: "Assign roles to users",
    description: "Attach or change role memberships (where not limited to admins).",
  },
  {
    code: "position.create",
    module: "position",
    action: "create",
    label: "Create positions",
    description: "Add new nodes to the org chart / position tree.",
  },
  {
    code: "position.update",
    module: "position",
    action: "update",
    label: "Update positions",
    description: "Edit position titles, levels, hierarchy, and metadata.",
  },
  {
    code: "position.assign",
    module: "position",
    action: "assign",
    label: "Assign positions",
    description: "Place users into specific positions (seat operations).",
  },
  {
    code: "workflow.submit",
    module: "workflow",
    action: "submit",
    label: "Send schema forms",
    description:
      "Send schema forms to external users via the External Forms tab. Level-1 employees create the external user, complete KYC, then dispatch the form.",
  },
  {
    code: "workflow.approve",
    module: "workflow",
    action: "approve",
    label: "Approve workflows",
    description:
      "Approve form submissions at your level. After approval the form moves to the next higher level in the org chain until the top level approves, triggering notifications all the way down to the level-1 employee and the external user.",
  },
  {
    code: "workflow.reject",
    module: "workflow",
    action: "reject",
    label: "Reject workflows",
    description:
      "Reject form submissions at your level with a mandatory reason. The rejection and reason are visible to all levels in the chain.",
  },
  {
    code: "workflow.status",
    module: "workflow",
    action: "status",
    label: "View workflow status",
    description:
      "See the list of workflows created by level-1 employees under you, with current status (pending / approved / rejected with reason) and who it is with.",
  },
  {
    code: "form.create",
    module: "form",
    action: "create",
    label: "Create forms",
    description: "Author or configure form definitions and schema.",
  },
  {
    code: "form.publish",
    module: "form",
    action: "publish",
    label: "Publish forms",
    description: "Publish forms for use and sharing.",
  },
  {
    code: "form.view",
    module: "form",
    action: "view",
    label: "Use forms",
    description: "Open the Forms area, fill forms, and view submissions you can access.",
  },
  {
    code: "report.view",
    module: "report",
    action: "view",
    label: "View reports",
    description: "Access reporting and analytics surfaces (also satisfies legacy notification gates).",
  },
  {
    code: "audit.view",
    module: "audit",
    action: "view",
    label: "View audit log",
    description: "Read security and compliance audit trails.",
  },
  {
    code: "tenant.manage",
    module: "tenant",
    action: "manage",
    label: "Manage tenant",
    description: "Full tenant administration: orgs, cross-tenant context, and elevated operations.",
  },
  {
    code: "tenant.send-credentials",
    module: "tenant",
    action: "send_credentials",
    label: "Send tenant credentials",
    description: "Send or resend login credentials to tenant administrators via email.",
  },
  {
    code: "kyc.create-user",
    module: "kyc",
    action: "create_user",
    label: "Create external user",
    description:
      "Create external users and open the KYC tab. This is the first step: level-1 employees create the external user here, verify KYC, then send a schema form from the External Forms tab.",
  },
  {
    code: "kyc.manage",
    module: "kyc",
    action: "manage",
    label: "Manage KYC",
    description:
      "Run KYC verification for external users: OTP, Aadhaar / PAN verification, status tracking. Also opens the KYC tab alongside kyc.create-user.",
  },
  {
    code: "notification.compose",
    module: "notification",
    action: "compose",
    label: "Send notifications",
    description: "Compose and send messages to eligible recipients (email, in-app, etc.).",
  },
];
